db_path: "../config.json"

config:
  msisdn:
    home:
      country_code: "+216"
      ndc_ranges:
        - [30, 35]
        - [50, 55]
      digits: 6
      count: 10
    national:
      country_code: "+216"
      ndc_ranges:
        - [20, 29]
        - [90, 99]
      digits: 6
      count: 10
    international:
      prefixes: ["+2126", "+336", "+441", "+491"]
      digits: 8
      count: 10
  network:
    mcc: "212"
    mnc: "01"
    3g:
      count: 10
    4g:
      count: 10
  bearer:
    Default Bearer:
      count: 3
      qos:
        gbr: 1
        mbr: 1000
    Dedicated Bearer:
      count: 3
      qos:
        gbr: 500
        mbr: 5000
    Video Bearer:
      count: 3
      qos:
        gbr: 1000
        mbr: 10000
